import createMjmlElement from "./createMjmlElement";

export { createMjmlElement };

export const Mjml = createMjmlElement("mjml");
export const MjmlAll = createMjmlElement("mj-all");
export const MjmlAccordion = createMjmlElement("mj-accordion");
export const MjmlAccordionElement = createMjmlElement("mj-accordion-element");
export const MjmlAccordionText = createMjmlElement("mj-accordion-text");
export const MjmlAccordionTitle = createMjmlElement("mj-accordion-title");
export const MjmlAttributes = createMjmlElement("mj-attributes");
export const MjmlBody = createMjmlElement("mj-body");
export const MjmlBreakpoint = createMjmlElement("mj-breakpoint");
export const MjmlButton = createMjmlElement("mj-button");
export const MjmlCarousel = createMjmlElement("mj-carousel");
export const MjmlCarouselImage = createMjmlElement("mj-carousel-image");
export const MjmlClass = createMjmlElement("mj-class");
export const MjmlColumn = createMjmlElement("mj-column");
export const MjmlDivider = createMjmlElement("mj-divider");
export const MjmlFont = createMjmlElement("mj-font");
export const MjmlGroup = createMjmlElement("mj-group");
export const MjmlHead = createMjmlElement("mj-head");
export const MjmlHero = createMjmlElement("mj-hero");
export const MjmlHtmlAttributes = createMjmlElement("mj-html-attributes");
export const MjmlHtmlAttribute = createMjmlElement("mj-html-attribute");
export const MjmlImage = createMjmlElement("mj-image");
export const MjmlNavbar = createMjmlElement("mj-navbar");
export const MjmlNavbarLink = createMjmlElement("mj-navbar-link");
export const MjmlPreview = createMjmlElement("mj-preview");
export const MjmlRaw = createMjmlElement("mj-raw");
export const MjmlSection = createMjmlElement("mj-section");
export const MjmlSelector = createMjmlElement("mj-selector");
export const MjmlSocial = createMjmlElement("mj-social");
export const MjmlSocialElement = createMjmlElement("mj-social-element");
export const MjmlSpacer = createMjmlElement("mj-spacer");
export const MjmlStyle = createMjmlElement("mj-style");
export const MjmlTable = createMjmlElement("mj-table");
export const MjmlText = createMjmlElement("mj-text");
export const MjmlTitle = createMjmlElement("mj-title");
export const MjmlWrapper = createMjmlElement("mj-wrapper");
